apiVersion: v2
name: overleaf-openshift
description: Overleaf CE+ with an arbitrary-UID image for OpenShift
version: 0.3.0
appVersion: "6.3.0-ext-v5.1"
type: application
kubeVersion: ">=1.25.0-0"
sources:
  - https://github.com/yu-i-i/overleaf-cep
  - https://github.com/overleaf/toolkit
  - https://github.com/overleaf/overleaf
