{{- if not .Values.secrets.existingSecret }}
{{- $name := printf "%s-secrets" (include "overleaf.fullname" .) }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $name | default dict }}
{{- $data := $secret.data | default dict }}
{{- $staging := index $data "STAGING_PASSWORD" | default (randAlphaNum 64 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "overleaf.labels" . | nindent 4 }}
type: Opaque
data:
  STAGING_PASSWORD: {{ $staging | quote }}
  V1_HISTORY_PASSWORD: {{ $staging | quote }}
  {{- range list "OVERLEAF_INVITE_TOKEN_SECRET" "WEB_API_PASSWORD" "CRYPTO_RANDOM" "OT_JWT_AUTH_KEY" }}
  {{ . }}: {{ index $data . | default (randAlphaNum 64 | b64enc) | quote }}
  {{- end }}
{{- end }}
